GET http://localhost:9090/api/product/products
###

GET http://localhost:9090/api/product/62/pictures
###

GET http://localhost:9090/api/product/62


###
POST http://localhost:9090/api/user/register
Content-Type: application/json

{
    "firstName":"Anny", "lastName":"Fabian","gender":"FEMALE","birthdate":"1999-04-29", "email":"te3st@korrekt.de", "password":"abcdefgH9!", "version":1.0
}

###
POST http://localhost:9090/api/user/login
Content-Type: application/json

{
    "email":"joghurta@nl.de" , "password":"ILikeJoghurt123."
}


###
POST http://localhost:9090/api/product/new
Content-Type: application/json

{
    "width":1.0, "height":1.0, "depth":3.0,"productType":"Stuhl", "roomType":"Bad", "nrAvailableItems":2,"description":"test 1234 string",
    "information":"sehr schicker stuhl jo","price":1.99, "name":"Hanspeter"
}

###
DELETE http://localhost:9090/api/product/114

###

DELETE http://localhost:9090/api/order/delete/1


###
GET http://localhost:9090/api/product/all/roomtypes


###
GET http://localhost:9090/api/product/all/producttypes

###
POST http://localhost:9090/api/product/product/new
Content-Type: application/json

{

    "articlenr" : 0,
    "name" : "Olloko",
    "productType" : "SINK",
    "roomType" : "BATHROOM",
    "price" : 120.0,
    "allPictures" : [ ],
    "height" : 20.0,
    "width" : 80.0,
    "depth" : 60.0,
    "allTags" : [ ],
    "available" : 90,
    "description" : "Verruecktes Waschbecken",
    "information" : "Der Wasserhahn laesst Harn herab"
  
}

